### ISSUE TITLE
Benchmark numbers in readme are not realistic

### ISSUE THREAD

**Issue by dtolnay** [madwire-media/serde-dbor#1]
There should be no way that 23 megabytes takes 6 seconds to serialize and 60 seconds to deserialize in CBOR, except for a bug in the benchmark code.

I tried the following benchmark using the [citm_catalog](https://github.com/FasterXML/jackson-dataformats-binary/blob/0d27d974a185cd6fad594d24122b3a26c5924c5b/cbor/src/test/resources/data/citm_catalog.json) file from Jackson's cbor test suite which contains a mix of strings and integers and arrays and objects. The numbers I get are cbor and dbor performing effectively the same, each 56x faster serialization and 79x faster deserialization than what you quoted in the readme for cbor.

Would you be able to share your benchmark code or else update the readme?

```rust
#![feature(test)]

macro_rules! bench {
    ($name:ident) => {
        mod $name {
            extern crate serde_cbor;
            extern crate serde_dbor;
            extern crate serde_json;
            extern crate test;

            #[bench]
            fn serialize(b: &mut test::Bencher) {
                let j = ::std::fs::read("citm_catalog.json").unwrap();
                let v: serde_cbor::Value = serde_json::from_slice(&j).unwrap();
                let array = [[[&v; 6]; 6]; 2];
                assert_eq!(serde_cbor::to_vec(&array).unwrap().len(), 24_650_871);

                b.iter(|| {
                    $name::to_vec(&array).unwrap();
                });
            }

            #[bench]
            fn deserialize(b: &mut test::Bencher) {
                let j = ::std::fs::read("citm_catalog.json").unwrap();
                let v: serde_cbor::Value = serde_json::from_slice(&j).unwrap();
                let array = [[[&v; 6]; 6]; 2];
                assert_eq!(serde_cbor::to_vec(&array).unwrap().len(), 24_650_871);

                let bytes = $name::to_vec(&array).unwrap();
                b.iter(|| {
                    let _: serde_cbor::Value = $name::from_slice(&bytes).unwrap();
                });
            }
        }
    };
}

bench!(serde_cbor);
bench!(serde_dbor);
```

```
test serde_cbor::deserialize ... bench: 760,235,792 ns/iter (+/- 38,549,073)
test serde_cbor::serialize   ... bench: 106,507,297 ns/iter (+/- 7,861,789)
test serde_dbor::deserialize ... bench: 768,901,025 ns/iter (+/- 36,597,615)
test serde_dbor::serialize   ... bench: 118,238,068 ns/iter (+/- 13,451,291)
```

**Comment by dqsully** [comment]
I can't post my test data file here because it contains proprietary data, but I can PM it to you if you want to test on it. The code I used for "benchmarking" is part of a proprietary service, and the numbers I got were from manually running the service a few times and averaging the times I got back. It's not a very robust benchmark by any means, but I did see dramatic and consistent differences. I posted a couple screenshots below from the logs of this service when it was loading this test data. It's grown since I tested for the Readme to about 47MB as CBOR, so the loading times are slower. And the DBOR file I used gets converted from CBOR whenever my service reads the original CBOR version, so they contain the exact same data.

Also, my service serializes/deserializes directly from the `File` as a reader and writer rather than reading the entire file into memory and then processing it. I have no doubt that the in-memory performance difference is negligible or nonexistent.

Loading (CBOR)
![screenshot_20180607_135757](https://user-images.githubusercontent.com/9079721/41123091-ca780374-6a5a-11e8-8519-86faff27c624.png)

Loading (DBOR)
![screenshot_20180607_135849](https://user-images.githubusercontent.com/9079721/41123142-e96a8b1c-6a5a-11e8-9375-200df64b1bcb.png)

---

I also just wrote this benchmark to test on this file:
```rust
#![feature(test)]

#[macro_use]
extern crate serde_derive;
extern crate serde;
extern crate serde_cbor;
extern crate serde_dbor;
extern crate test;

use std::collections::BTreeMap;

#[derive(Serialize, Deserialize)]
struct StructA {
    a: u64,
    b: u64,
    c: u64,
    d: u64,
    e: u64,
    f: u64,
}
#[derive(Serialize, Deserialize)]
struct StructB {
    a: u64,
    b: u64,
    c: u64,
    d: u64,
    e: u64,
    f: u64,
    g: u64,
    h: u64,
    i: u64,
}

type MyValue = BTreeMap<
    String,
    BTreeMap<
        String,
        BTreeMap<
            u8,
            BTreeMap<
                u8,
                (StructA, StructB)
            >
        >
    >
>;

mod serde_cbor_test {
    use super::*;

    #[bench]
    fn serialize_fs(b: &mut test::Bencher) {
        let data: MyValue = serde_dbor::from_reader(::std::fs::File::open("test.dbor").unwrap()).unwrap();

        b.iter(|| {
            let mut file = ::std::fs::File::create("output").unwrap();
            serde_cbor::to_writer(&mut file, &data).unwrap();
        });
    }


    #[bench]
    fn deserialize_fs(b: &mut test::Bencher) {
        b.iter(|| {
            let _: MyValue = serde_cbor::from_reader(::std::fs::File::open("test.cbor").unwrap()).unwrap();
        });
    }
}

mod serde_dbor_test {
    use super::*;

    #[bench]
    fn serialize_fs(b: &mut test::Bencher) {
        let data: MyValue = serde_dbor::from_reader(::std::fs::File::open("test.dbor").unwrap()).unwrap();

        b.iter(|| {
            let mut file = ::std::fs::File::create("output").unwrap();
            serde_dbor::to_writer(&data, &mut file).unwrap();
        });
    }


    #[bench]
    fn deserialize_fs(b: &mut test::Bencher) {
        b.iter(|| {
            let _: MyValue = serde_dbor::from_reader(::std::fs::File::open("test.dbor").unwrap()).unwrap();
        });
    }
}
```

I had an error in the serialization tests so I don't have those results yet, but I was able to test the deserialization properly.

```
test serde_cbor_test::deserialize_fs ... bench: 13,010,045,263 ns/iter (+/- 914,849,539)
test serde_cbor_test::serialize_fs   ... FAILED
test serde_dbor_test::deserialize_fs ... bench: 752,869,640 ns/iter (+/- 48,440,128)
test serde_dbor_test::serialize_fs   ... FAILED
```

I will run the fixed benchmark code overnight and post the results tomorrow.

**Comment by dtolnay** [comment]
Using `to_writer` or `from_reader` with a `std::fs::File` is never what you want when performance matters, so formats generally do not optimize for this. You always at least want a [`BufWriter`](https://doc.rust-lang.org/std/io/struct.BufWriter.html) or [`BufReader`](https://doc.rust-lang.org/std/io/struct.BufReader.html) around the File, but handling bytes in memory and reading/writing the file all at once will always be faster than to_writer/from_reader if the data fits in memory, often by a factor of 100x.

**Comment by dqsully** [comment]
Ok, somehow I never learned about `BufWriter` and `BufReader` which is my fault, so I've removed the benchmark claims from the Readme. Just for curiosity though I'll still post my full benchmark results when they're done, including now with and without `BufReader` and `BufWriter`.

**Comment by dqsully** [comment]
I had to skip the unbuffered CBOR benchmarks because they took way too long and I used a smaller test file this time just for faster tests. I also regenerated my CBOR test file since it was from an older version of `serde_cbor` and the deserialization/serialization process with the old file was not idempotent anymore with the `serde_cbor` updates. And, for more consistency, I slightly underclocked my cpu so it didn't constantly cycle between boosting and thermal throttling.

Also, I found a bug in my code through this benchmark, which is why the `serde_dbor_test::deserialize_fs_buf` test failed.

```
test serde_cbor_test::deserialize_fs_buf   ... bench: 925,367,302 ns/iter (+/- 12,911,121)
test serde_cbor_test::deserialize_mem      ... bench: 509,141,368 ns/iter (+/- 10,578,861)
test serde_cbor_test::serialize_fs_buf     ... bench: 290,658,058 ns/iter (+/- 69,648,168)
test serde_cbor_test::serialize_mem        ... bench: 148,444,588 ns/iter (+/- 34,108,958)

test serde_dbor_test::deserialize_fs_buf   ... FAILED
test serde_dbor_test::deserialize_fs_nobuf ... bench: 268,144,977 ns/iter (+/- 29,462,222)
test serde_dbor_test::deserialize_mem      ... bench: 257,042,722 ns/iter (+/- 26,029,529)
test serde_dbor_test::serialize_fs_buf     ... bench: 143,806,205 ns/iter (+/- 28,553,550)
test serde_dbor_test::serialize_fs_nobuf   ... bench: 268,525,574 ns/iter (+/- 78,858,852)
test serde_dbor_test::serialize_mem        ... bench: 109,821,196 ns/iter (+/- 4,691,235)
```

Benchmark code is here for brevity: https://gist.github.com/dqsully/a557093eb5c0d48845dbe1fa604ecc61

For whatever reason there are still significant performance differences, and I couldn't tell you definitively why - I'm no programming expert by any means.

My io implementation for DBOR is buffered in 1KB chunks, which I think is why loading from a file and loading from memory performed very similar. But I must have a terrible buffered output implementation because the standard library's `BufWriter` still about doubled my write performance. Then of course writing directly to memory is still faster than writing to disk, this time by about 30%.

As for the difference between CBOR and DBOR in-memory performance, I think it might have to do with endianness, since I made DBOR numbers little endian to optimize for x86.

I think I'm going to try testing my library without the built-in buffering just to see what happens, and maybe with 4KB buffering too since that's the default Linux page size.
